# 
policy_path: "{LEGGED_GYM_ROOT_DIR}/logs/h1/exported/policies/policy_lstm_1.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/h1/scene.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [150, 150, 150, 200, 40,  150, 150, 150, 200, 40]
kds: [2, 2, 2, 4, 2,  2, 2, 2, 4, 2]

default_angles: [0,  0.0,  -0.1,  0.3, -0.2,
                 0,  0.0,  -0.1,  0.3, -0.2]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 10
num_obs: 41

cmd_init: [0.5, 0, 0]